# This configuration has been generated by the Azure deployments handler which utilizes Generative AI which may result in unintended or inaccurate configuration code. A human must validate that this configuration accomplishes the desired goal before applying the configuration.
variable "bkstrgrg" {
  type        = string
  description = "The name of the backend storage account resource group"
  default     = "MYFIRSTRG"
}

variable "bkstrg" {
  type        = string
  description = "The name of the backend storage account"
  default     = "backendstorageterra"
}

variable "bkcontainer" {
  type = string
  description = "The container name for the backend config"
  default = "terraformstate"
}

variable "bkstrgkey" {
  type = string
  description = "The access key for the storage account"
  default = "terraform.tfstateVM"
}

variable "prefix" {
  default = "tfvmex"
}

variable "location" {
  type    = string
  default = "EastUS"
}

variable "vms" {
  type = map(object({
    name = string
    sku  = string
  }))
  default = {
    "vm1" = { name = "vm1", sku = "Standard_D2as_v6" }
    "vm2" = { name = "vm2", sku = "Standard_D2ads_v6"}
    "vm3" = { name = "vm3", sku = "Standard_D2als_v6" }
  }
}

variable "existing_virtual_network_name" {
  type    = string
  default = "Myfirstvnet"
}

variable "existing_resource_group_name" {
  type    = string
  default = "vnetrg"
}

variable "existing_subnet_name" {
  type    = string
  default = "subnet_1"
}
